### ISSUE TITLE
Implementing a scorebar

### ISSUE THREAD

**Issue by TRMSC** [otacke/h5p-jigsaw-puzzle#18]
It would be nice and helpful to have a typically h5p scorebar for getting the star/ point after solving a puzzle. 
Is it planned or possible to implement this feature?

**Comment by otacke** [comment]
@TRMSC Have you read the readme of this repository?

**Comment by TRMSC** [comment]
Thanks for your feedback. Yes I had read it and I also know the pages for developing h5p. Until now I don't have the skills for going on with this - otherwise I would like to participate by eg a pull request.

**Comment by TRMSC** [comment]
Thanks for your feedback! Of course I understand that now.

**Comment by otacke** [comment]
@TRMSC Well, as I wrote in the readme: I may work on this content type again even though it was contract work, but I definitely don't have any plans. For this case: Having a scorebar feels a little weird, as it would either be 0 or full score and pulling some stunt like "Find Multiple Hotspots" does with sending an xAPI answer statement for every correct answer is not something I'd like to implement.

**Comment by TRMSC** [comment]
Thanks for the words. I only thought that it would be appropriate having a feedback for users after the task is done. But it only was an idea, no assignment or something. The jigsaw puzzle is a great content type even without that feature of course.

**Comment by otacke** [comment]
@TRMSC And that's a good idea! But the content type as is met my customer's requirements (including stripping out some features that their version has, cmp. https://youtu.be/vKxqW__9ge8). Without me raising my voice for an openly available version and putting in extra unpaid effort there would be no Jigsaw puzzle for the H5P community to play with. My excitement about now being adressed for free maintenance is somewhat limited :-)

**Comment by TRMSC** [comment]
That's absolutely understandable and I appreciate your explanation. That helps me internalizing the development structures for this case. I am working on being able to actively participate in h5p developments someday. :-)

**Comment by otacke** [comment]
@TRMSC 👍
